server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://namdevaniket446:TOd09Wqu32PHamYn@cms.dtgydnp.mongodb.net/?retryWrites=true&w=majority&appName=cms
      database: Hook4Startup-dev
      auto-index-creation: true
  web:
    resources:
      static-locations: classpath:/static/  # ✅ yaha '=' ki jagah ':' hoga

application:
  name: hook4startup

logging:
  level:
    org.springframework.security: DEBUG  # ✅ '=' ko ':' se replace karo
